import Link from "next/link";
import Head from "next/head";
import Image from "next/image";

export default function home() {
  return (
    <>
      <Head>
        <title>Cakey World</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center">
        <Image alt="Cakey World" height={544} src="/cake.jpg" width={816} />
        </main>
    </>
  );
}
